[plat]
# The base address of the user space.
user-space-base = 0x1000
# The base address for user interpreter.
user-interp-base = 0x400_0000
# The size of the user space.
user-space-size = 0x3f_ffff_f000

# The highest address of the user stack.
user-stack-top = 0x4_0000_0000
# The size of the user stack.
user-stack-size = 0x1_0000

# The lowest address of the user heap.
user-heap-base = 0x4000_0000
# The size of the user heap.
user-heap-size = 0x1_0000

# The size of the kernel stack.
kernel-stack-size = 0x40000
